# renew_before_expiry = 30 days
version = 2.9.0
archive_dir = /etc/letsencrypt/archive/isp.picloud.in
cert = /etc/letsencrypt/live/isp.picloud.in/cert.pem
privkey = /etc/letsencrypt/live/isp.picloud.in/privkey.pem
chain = /etc/letsencrypt/live/isp.picloud.in/chain.pem
fullchain = /etc/letsencrypt/live/isp.picloud.in/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = d20bb773c97de5f44f933ba3bf33c3c3
pref_challs = dns-01,
authenticator = manual
manual_auth_hook = /opt/isp/ssl/acmedns-auth-hook.sh
manual_cleanup_hook = /opt/isp/ssl/manual-cleanup-hook.sh
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
